# Configuraci贸n de la aplicaci贸n
spring:
  application:
    name: kardex
  data:
    mongodb:
      uri: mongodb+srv://cristopherguzman:orTIWL10NmFAo3S5@cluster0.o8sc9.mongodb.net/kardex?retryWrites=true&w=majority&appName=Cluster0
      database: kardex

# Configuraci贸n del servidor
server:
  port: 8080

# Configuraci贸n de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true